artifact_location: /Users/musakhan/Documents/Practice/BanglaOCR/artifacts/mlflow/990941922252886375
creation_time: 1780156197767
experiment_id: '990941922252886375'
last_update_time: 1780156197767
lifecycle_stage: active
name: bangla-ocr-training
trace_location: null
workspace: default
